In [4]:
# Import the dependencies
import os
import requests
import pandas as pd

In [2]:
# 3/16/2022 supply data CSV from CAISO Network XHR
url = 'https://www.caiso.com/outlook/SP/History/20220316/fuelsource.csv?_=1647651289493'

In [3]:
# Save CSV to local machine
proxies = {}
response = requests.get(url=url, proxies=proxies)
with open('supply_2022_03_16.csv', 'wb') as f:
    f.write(response.content)

In [7]:
# Save CSV to DataFrame
supply_2022_03_16_df = pd.read_csv(url)
supply_2022_03_16_df.head()

,Time,Solar,Wind,Geothermal,Biomass,Biogas,Small hydro,Coal,Nuclear,Natural Gas,Large Hydro,Batteries,Imports,Other
0,00:00,-43,4894,900,281,194,161,10,2127,5353,1087,-88,7819,0
1,00:05,-43,5024,900,279,194,160,11,2127,5197,1004,-3,7857,0
2,00:10,-43,5076,899,285,194,151,11,2127,5060,869,-8,8022,0
3,00:15,-42,5098,900,285,194,140,10,2126,5024,872,-18,8017,0
4,00:20,-42,5070,899,284,194,141,11,2128,4928,873,21,8051,0